-- Create draft and live schemas for content
CREATE SCHEMA IF NOT EXISTS draft;
CREATE SCHEMA IF NOT EXISTS live;
SET search_path TO draft, live, public;

CREATE TABLE draft.pages(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID UNIQUE DEFAULT uuidv7() NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    weight INTEGER DEFAULT 5,
    start TIMESTAMPTZ,
    "end" TIMESTAMPTZ,
    page_type TEXT,
    current_page_version_id BIGINT,
    original JSON,
    page_id BIGINT,
    FOREIGN KEY (page_id) REFERENCES draft.pages (id) ON DELETE CASCADE
);

CREATE TRIGGER updated_at
    BEFORE UPDATE ON draft.pages
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TABLE draft.page_tags(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID UNIQUE DEFAULT uuidv7() NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    page_id BIGINT,
    tag_id BIGINT NOT NULL,
    weight INTEGER DEFAULT 5,
    FOREIGN KEY (page_id) REFERENCES draft.pages (id) ON DELETE CASCADE
);

CREATE TRIGGER updated_at
    BEFORE UPDATE ON draft.page_tags
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();


CREATE TABLE live.pages(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID UNIQUE DEFAULT uuidv7() NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    weight INTEGER DEFAULT 5,
    start TIMESTAMPTZ,
    "end" TIMESTAMPTZ,
    page_type TEXT,
    current_page_version_id BIGINT,
    original JSON,
    page_id BIGINT,
    FOREIGN KEY (page_id) REFERENCES live.pages (id) ON DELETE CASCADE
);

CREATE TRIGGER updated_at
    BEFORE UPDATE ON live.pages
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TABLE live.page_tags(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID UNIQUE DEFAULT uuidv7() NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    page_id BIGINT,
    tag_id BIGINT NOT NULL,
    weight INTEGER DEFAULT 5,
    FOREIGN KEY (page_id) REFERENCES live.pages (id) ON DELETE CASCADE
);

CREATE TRIGGER updated_at
    BEFORE UPDATE ON live.page_tags
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();
