-- Create mail schema
CREATE SCHEMA IF NOT EXISTS mail;
SET search_path TO mail, public;

CREATE TABLE mail.mail(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID UNIQUE DEFAULT uuidv7() NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    domain TEXT,
    service TEXT NOT NULL,
    ip TEXT NOT NULL,
    entity TEXT,
    entity_id TEXT,
    sender TEXT NOT NULL,
    recipient TEXT NOT NULL,
    cc TEXT,
    bcc TEXT,
    subject TEXT,
    text TEXT,
    html TEXT,
    tokens TEXT,
    result TEXT
);

CREATE TRIGGER updated_at
    BEFORE UPDATE ON mail.mail
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TABLE mail.unsubscribes(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID UNIQUE DEFAULT uuidv7() NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    message_id TEXT NOT NULL,
    recipient TEXT NOT NULL
);

CREATE TRIGGER updated_at
    BEFORE UPDATE ON mail.unsubscribes
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();
