import packageJson from '../package.json'

export default new Map<string, any>([
  ['layout/default',              { package: packageJson.name, payload: await import('./layout/default.liquid') }],
  ['layout/admin/default',        { package: packageJson.name, payload: await import('./layout/admin/default.liquid') }],
  ['sections/admin/edit/main',    { package: packageJson.name, payload: await import('./sections/admin/edit/main.liquid') }],
  ['sections/breadcrumb',         { package: packageJson.name, payload: await import('./sections/breadcrumb.liquid') }],
  ['sections/dev-footer',         { package: packageJson.name, payload: await import('./sections/dev-footer.liquid') }],
  ['sections/footnote',           { package: packageJson.name, payload: await import('./sections/footnote.liquid') }],
  ['sections/header',             { package: packageJson.name, payload: await import('./sections/header.liquid') }],
  ['sections/hero',               { package: packageJson.name, payload: await import('./sections/hero.liquid') }],
  ['sections/orm-header',         { package: packageJson.name, payload: await import('./sections/orm-header.liquid') }],
  ['sections/orm-list',           { package: packageJson.name, payload: await import('./sections/orm-list.liquid') }],
  ['sections/pagination',         { package: packageJson.name, payload: await import('./sections/pagination.liquid') }],
  ['sections/paragraphs',         { package: packageJson.name, payload: await import('./sections/paragraphs.liquid') }],
  ['snippets/admin/nav',          { package: packageJson.name, payload: await import('./snippets/admin/nav.liquid') }],
  ['snippets/edit_belongs',       { package: packageJson.name, payload: await import('./snippets/edit_belongs.liquid') }],
  ['snippets/edit_fields',        { package: packageJson.name, payload: await import('./snippets/edit_fields.liquid') }],
  ['snippets/edit_filter',        { package: packageJson.name, payload: await import('./snippets/edit_filter.liquid') }],
  ['snippets/edit_has_many',      { package: packageJson.name, payload: await import('./snippets/edit_has_many.liquid') }],
  ['snippets/edit_many',          { package: packageJson.name, payload: await import('./snippets/edit_many.liquid') }],
  ['snippets/logo',               { package: packageJson.name, payload: await import('./snippets/logo.liquid') }],
  ['snippets/head/tailwindcss',   { package: packageJson.name, payload: await import('./snippets/head/tailwindcss.liquid') }],
  ['templates/error',             { package: packageJson.name, payload: await import('./templates/error.liquid') }],
  ['templates/admin/dialog',      { package: packageJson.name, payload: await import('./templates/admin/dialog.liquid') }],
  ['templates/admin/edit',        { package: packageJson.name, payload: await import('./templates/admin/edit.liquid') }],
  ['templates/admin/edit.json',   { package: packageJson.name, payload: await import('./templates/admin/edit.json') }],
  ['templates/page.json',         { package: packageJson.name, payload: await import('./templates/page.json') }],
])
